let firstname = "Pranabesh";
let lastname = 'Basu';
let rollNo = '19';
let Sec = 'C';
let fullname = 'My name is "Pranabesh Basu".';
console.log(firstname);
console.log(lastname);
console.log(rollNo);
console.log(Sec);
console.log(fullname);
console.log(firstname[5]);
console.log(lastname[-1]);
let newfullname = firstname + " " + lastname;
console.log(newfullname);
console.log(newfullname.length);